/**
 * Starter catalogue.
 *
 * ⚠️  THE NUTRITION AND INGREDIENT DATA BELOW IS INDICATIVE.
 *
 * Every value must be replaced with the figures printed on the pack you
 * actually import, before the product is made active. Publishing a
 * nutrition declaration that does not match the goods is a labelling
 * offence, not a cosmetic bug — and under art. 8(1) of Reg. 1169/2011 the
 * importer named on the label answers for it.
 *
 * The shape is right; the numbers are placeholders.
 */

import type { Allergen, DurabilityKind, NetQuantityUnit, VatCategory } from '@prisma/client';

export interface SeedProduct {
  slug: string;
  categorySlug: string;
  displayNameFr: string;
  displayNameEn: string;
  displayNameAr: string;
  legalName: string;
  brand: string | null;
  countryOfOrigin: string;
  descriptionFr: string;
  ingredientsFr: string;
  allergens: Allergen[];
  mayContain: Allergen[];
  quidFr: string | null;
  netQuantityValue: number;
  netQuantityUnit: NetQuantityUnit;
  netQuantityDrained: number | null;
  energyKj: number;
  energyKcal: number;
  fat: number;
  saturates: number;
  carbohydrate: number;
  sugars: number;
  protein: number;
  salt: number;
  fibre: number | null;
  durabilityKind: DurabilityKind;
  storageConditionsFr: string;
  usageInstructionsFr: string | null;
  priceCents: number;
  vatCategory: VatCategory;
  shippingWeightGrams: number;
  isFeatured: boolean;
}

export const CATEGORIES = [
  { slug: 'epicerie-salee', nameFr: 'Épicerie salée', nameEn: 'Savoury pantry', nameAr: 'مونة مالحة', position: 1 },
  { slug: 'huiles-condiments', nameFr: 'Huiles & condiments', nameEn: 'Oils & condiments', nameAr: 'زيوت وتوابل', position: 2 },
  { slug: 'epices-herbes', nameFr: 'Épices & herbes', nameEn: 'Spices & herbs', nameAr: 'بهارات وأعشاب', position: 3 },
  { slug: 'cereales-legumineuses', nameFr: 'Céréales & légumineuses', nameEn: 'Grains & pulses', nameAr: 'حبوب وبقوليات', position: 4 },
  { slug: 'cafe-boissons', nameFr: 'Café & boissons', nameEn: 'Coffee & drinks', nameAr: 'قهوة ومشروبات', position: 5 },
  { slug: 'douceurs', nameFr: 'Douceurs & pâtisseries', nameEn: 'Sweets & pastries', nameAr: 'حلويات', position: 6 },
  { slug: 'fruits-secs-noix', nameFr: 'Fruits secs & noix', nameEn: 'Dried fruit & nuts', nameAr: 'مكسرات وفواكه مجففة', position: 7 },
] as const;

export const PRODUCTS: SeedProduct[] = [
  {
    slug: 'tahini-450g',
    categorySlug: 'huiles-condiments',
    displayNameFr: 'Tahini — purée de sésame 450 g',
    displayNameEn: 'Tahini — sesame paste 450 g',
    displayNameAr: 'طحينة ٤٥٠ غ',
    legalName: 'Purée de graines de sésame décortiquées grillées',
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: "La base du houmous et du taratour. Sésame grillé et broyé à la meule de pierre, sans additif.",
    ingredientsFr: 'Graines de **sésame** décortiquées grillées 100 %.',
    allergens: ['SESAME'],
    mayContain: ['NUTS', 'PEANUTS'],
    quidFr: 'Sésame 100 %',
    netQuantityValue: 450, netQuantityUnit: 'G', netQuantityDrained: null,
    energyKj: 2614, energyKcal: 631, fat: 54, saturates: 7.6,
    carbohydrate: 10, sugars: 0.5, protein: 21, salt: 0.02, fibre: 9.3,
    durabilityKind: 'DDM',
    storageConditionsFr: "À conserver dans un endroit frais et sec, à l'abri de la lumière. Après ouverture, conserver au réfrigérateur.",
    usageInstructionsFr: "Remuer avant emploi : la séparation de l'huile est naturelle.",
    priceCents: 590, vatCategory: 'FOOD_REDUCED', shippingWeightGrams: 500, isFeatured: true,
  },
  {
    slug: 'zaatar-200g',
    categorySlug: 'epices-herbes',
    displayNameFr: "Zaatar libanais 200 g",
    displayNameEn: 'Lebanese za\'atar 200 g',
    displayNameAr: 'زعتر لبناني ٢٠٠ غ',
    legalName: 'Mélange d\'épices à base de thym, sumac et graines de sésame',
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: "Le mélange du petit-déjeuner libanais : thym sauvage, sumac acidulé et sésame grillé.",
    ingredientsFr: 'Thym 45 %, graines de **sésame** grillées 30 %, sumac 20 %, sel.',
    allergens: ['SESAME'],
    mayContain: [],
    quidFr: 'Thym 45 %, sésame 30 %, sumac 20 %',
    netQuantityValue: 200, netQuantityUnit: 'G', netQuantityDrained: null,
    energyKj: 1465, energyKcal: 350, fat: 15, saturates: 2.5,
    carbohydrate: 30, sugars: 2, protein: 10, salt: 6.0, fibre: 20,
    durabilityKind: 'DDM',
    storageConditionsFr: 'À conserver dans un endroit frais et sec, à l\'abri de la lumière.',
    usageInstructionsFr: "Mélanger à de l'huile d'olive et étaler sur du pain avant cuisson (manouché).",
    priceCents: 450, vatCategory: 'FOOD_REDUCED', shippingWeightGrams: 230, isFeatured: true,
  },
  {
    slug: 'huile-olive-750ml',
    categorySlug: 'huiles-condiments',
    displayNameFr: "Huile d'olive vierge extra 750 ml",
    displayNameEn: 'Extra virgin olive oil 750 ml',
    displayNameAr: 'زيت زيتون بكر ممتاز ٧٥٠ مل',
    legalName: 'Huile d\'olive vierge extra',
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: "Première pression à froid, oliviers du Koura. Fruité, légèrement poivré en finale.",
    ingredientsFr: "Huile d'olive vierge extra 100 %.",
    allergens: [],
    mayContain: [],
    quidFr: null,
    netQuantityValue: 750, netQuantityUnit: 'ML', netQuantityDrained: null,
    energyKj: 3389, energyKcal: 824, fat: 91.6, saturates: 13.8,
    carbohydrate: 0, sugars: 0, protein: 0, salt: 0, fibre: null,
    durabilityKind: 'DDM',
    storageConditionsFr: "À conserver à l'abri de la lumière et de la chaleur.",
    usageInstructionsFr: null,
    priceCents: 1490, vatCategory: 'FOOD_REDUCED', shippingWeightGrams: 1100, isFeatured: true,
  },
  {
    slug: 'melasse-grenade-350ml',
    categorySlug: 'huiles-condiments',
    displayNameFr: 'Mélasse de grenade 350 ml',
    displayNameEn: 'Pomegranate molasses 350 ml',
    displayNameAr: 'دبس رمان ٣٥٠ مل',
    legalName: 'Concentré de jus de grenade',
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: "Acidulée et sombre, indispensable au fattoush et au mouhammara.",
    ingredientsFr: 'Jus de grenade concentré 100 %.',
    allergens: [],
    mayContain: [],
    quidFr: null,
    netQuantityValue: 350, netQuantityUnit: 'ML', netQuantityDrained: null,
    energyKj: 1190, energyKcal: 280, fat: 0, saturates: 0,
    carbohydrate: 68, sugars: 62, protein: 0.5, salt: 0.05, fibre: null,
    durabilityKind: 'DDM',
    storageConditionsFr: 'À conserver dans un endroit frais et sec. Après ouverture, conserver au réfrigérateur.',
    usageInstructionsFr: null,
    priceCents: 690, vatCategory: 'FOOD_REDUCED', shippingWeightGrams: 550, isFeatured: false,
  },
  {
    slug: 'eau-fleur-oranger-250ml',
    categorySlug: 'cafe-boissons',
    displayNameFr: "Eau de fleur d'oranger 250 ml",
    displayNameEn: 'Orange blossom water 250 ml',
    displayNameAr: 'ماء زهر ٢٥٠ مل',
    legalName: "Eau distillée de fleur d'oranger",
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: "Distillation traditionnelle. Quelques gouttes suffisent à parfumer un dessert ou un café blanc.",
    ingredientsFr: "Eau, distillat de fleur d'oranger.",
    allergens: [],
    mayContain: [],
    quidFr: null,
    netQuantityValue: 250, netQuantityUnit: 'ML', netQuantityDrained: null,
    energyKj: 0, energyKcal: 0, fat: 0, saturates: 0,
    carbohydrate: 0, sugars: 0, protein: 0, salt: 0, fibre: null,
    durabilityKind: 'DDM',
    storageConditionsFr: "À conserver à l'abri de la lumière.",
    usageInstructionsFr: null,
    priceCents: 420, vatCategory: 'FOOD_REDUCED', shippingWeightGrams: 400, isFeatured: false,
  },
  {
    slug: 'halva-pistache-400g',
    categorySlug: 'douceurs',
    displayNameFr: 'Halva à la pistache 400 g',
    displayNameEn: 'Pistachio halva 400 g',
    displayNameAr: 'حلاوة بالفستق ٤٠٠ غ',
    legalName: 'Confiserie à base de purée de sésame et de sucre, aux pistaches',
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: 'Texture friable, sésame grillé et éclats de pistache.',
    ingredientsFr: 'Purée de **sésame** 50 %, sucre, **pistaches** 8 %, extrait de racine de saponaire.',
    allergens: ['SESAME', 'NUTS'],
    mayContain: ['MILK'],
    quidFr: 'Sésame 50 %, pistaches 8 %',
    netQuantityValue: 400, netQuantityUnit: 'G', netQuantityDrained: null,
    energyKj: 2255, energyKcal: 540, fat: 32, saturates: 5,
    carbohydrate: 50, sugars: 42, protein: 12, salt: 0.1, fibre: 4,
    durabilityKind: 'DDM',
    storageConditionsFr: 'À conserver dans un endroit frais et sec.',
    usageInstructionsFr: null,
    // Confiserie — 20 % once the franchise ends, not the 5,5 % food rate.
    priceCents: 750, vatCategory: 'CONFECTIONERY', shippingWeightGrams: 450, isFeatured: true,
  },
  {
    slug: 'cafe-cardamome-200g',
    categorySlug: 'cafe-boissons',
    displayNameFr: 'Café libanais moulu à la cardamome 200 g',
    displayNameEn: 'Lebanese ground coffee with cardamom 200 g',
    displayNameAr: 'قهوة لبنانية بالهال ٢٠٠ غ',
    legalName: 'Café torréfié moulu aromatisé à la cardamome',
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: 'Torréfaction foncée, mouture très fine pour la cafetière rakwé.',
    ingredientsFr: 'Café torréfié moulu 95 %, cardamome 5 %.',
    allergens: [],
    mayContain: [],
    quidFr: 'Cardamome 5 %',
    netQuantityValue: 200, netQuantityUnit: 'G', netQuantityDrained: null,
    energyKj: 950, energyKcal: 227, fat: 14, saturates: 6.5,
    carbohydrate: 39, sugars: 0, protein: 12, salt: 0.01, fibre: 37,
    durabilityKind: 'DDM',
    storageConditionsFr: 'À conserver dans un endroit frais et sec, en emballage hermétique après ouverture.',
    usageInstructionsFr: 'Une cuillère à café bombée par tasse. Porter à ébullition trois fois.',
    priceCents: 690, vatCategory: 'FOOD_REDUCED', shippingWeightGrams: 230, isFeatured: false,
  },
  {
    slug: 'freekeh-500g',
    categorySlug: 'cereales-legumineuses',
    displayNameFr: 'Freekeh — blé vert grillé 500 g',
    displayNameEn: 'Freekeh — roasted green wheat 500 g',
    displayNameAr: 'فريكة ٥٠٠ غ',
    legalName: 'Blé vert immature grillé concassé',
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: 'Récolté vert puis grillé au feu de bois : un goût fumé caractéristique.',
    ingredientsFr: '**Blé** vert grillé concassé 100 %.',
    allergens: ['GLUTEN'],
    mayContain: [],
    quidFr: null,
    netQuantityValue: 500, netQuantityUnit: 'G', netQuantityDrained: null,
    energyKj: 1465, energyKcal: 350, fat: 2.5, saturates: 0.4,
    carbohydrate: 62, sugars: 1, protein: 12, salt: 0.01, fibre: 13,
    durabilityKind: 'DDM',
    storageConditionsFr: 'À conserver dans un endroit frais et sec.',
    usageInstructionsFr: 'Rincer, puis cuire 20 à 25 minutes dans deux fois son volume d\'eau.',
    priceCents: 480, vatCategory: 'FOOD_REDUCED', shippingWeightGrams: 540, isFeatured: false,
  },
  {
    slug: 'boulgour-fin-1kg',
    categorySlug: 'cereales-legumineuses',
    displayNameFr: 'Boulgour fin 1 kg',
    displayNameEn: 'Fine bulgur 1 kg',
    displayNameAr: 'برغل ناعم ١ كغ',
    legalName: 'Blé dur précuit concassé fin',
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: 'Mouture fine, celle du taboulé.',
    ingredientsFr: '**Blé** dur précuit concassé 100 %.',
    allergens: ['GLUTEN'],
    mayContain: [],
    quidFr: null,
    netQuantityValue: 1, netQuantityUnit: 'KG', netQuantityDrained: null,
    energyKj: 1432, energyKcal: 342, fat: 1.3, saturates: 0.2,
    carbohydrate: 68, sugars: 0.4, protein: 12, salt: 0.01, fibre: 18,
    durabilityKind: 'DDM',
    storageConditionsFr: 'À conserver dans un endroit frais et sec.',
    usageInstructionsFr: null,
    priceCents: 390, vatCategory: 'FOOD_REDUCED', shippingWeightGrams: 1050, isFeatured: false,
  },
  {
    slug: 'pois-chiches-1kg',
    categorySlug: 'cereales-legumineuses',
    displayNameFr: 'Pois chiches secs 1 kg',
    displayNameEn: 'Dried chickpeas 1 kg',
    displayNameAr: 'حمص حب ١ كغ',
    legalName: 'Pois chiches secs',
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: 'Gros calibre, peau fine — pour un houmous crémeux.',
    ingredientsFr: 'Pois chiches secs 100 %.',
    allergens: [],
    mayContain: ['GLUTEN'],
    quidFr: null,
    netQuantityValue: 1, netQuantityUnit: 'KG', netQuantityDrained: null,
    energyKj: 1523, energyKcal: 364, fat: 6, saturates: 0.6,
    carbohydrate: 55, sugars: 10, protein: 19, salt: 0.02, fibre: 17,
    durabilityKind: 'DDM',
    storageConditionsFr: 'À conserver dans un endroit frais et sec.',
    usageInstructionsFr: 'Faire tremper 12 heures, puis cuire 1 à 2 heures.',
    priceCents: 350, vatCategory: 'FOOD_REDUCED', shippingWeightGrams: 1050, isFeatured: false,
  },
  {
    slug: 'feuilles-vigne-400g',
    categorySlug: 'epicerie-salee',
    displayNameFr: 'Feuilles de vigne en saumure 400 g',
    displayNameEn: 'Vine leaves in brine 400 g',
    displayNameAr: 'ورق عنب ٤٠٠ غ',
    legalName: 'Feuilles de vigne en saumure',
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: 'Feuilles jeunes et souples, prêtes à farcir.',
    ingredientsFr: 'Feuilles de vigne 60 %, eau, sel, correcteur d\'acidité : acide citrique.',
    allergens: [],
    mayContain: [],
    quidFr: 'Feuilles de vigne 60 %',
    netQuantityValue: 400, netQuantityUnit: 'G', netQuantityDrained: 200,
    energyKj: 290, energyKcal: 69, fat: 0.4, saturates: 0.1,
    carbohydrate: 6, sugars: 0.5, protein: 4, salt: 4.5, fibre: 11,
    durabilityKind: 'DDM',
    storageConditionsFr: 'À conserver dans un endroit frais et sec. Après ouverture, conserver au réfrigérateur et consommer sous 5 jours.',
    usageInstructionsFr: "Rincer abondamment à l'eau froide avant utilisation pour retirer l'excès de sel.",
    priceCents: 490, vatCategory: 'FOOD_REDUCED', shippingWeightGrams: 600, isFeatured: false,
  },
  {
    slug: 'abricots-secs-250g',
    categorySlug: 'fruits-secs-noix',
    displayNameFr: 'Abricots secs 250 g',
    displayNameEn: 'Dried apricots 250 g',
    displayNameAr: 'مشمش مجفف ٢٥٠ غ',
    legalName: 'Abricots secs',
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: 'Moelleux, sucrés, sans sucre ajouté.',
    ingredientsFr: 'Abricots secs, conservateur : **anhydride sulfureux**.',
    allergens: ['SULPHITES'],
    mayContain: ['NUTS'],
    quidFr: null,
    netQuantityValue: 250, netQuantityUnit: 'G', netQuantityDrained: null,
    energyKj: 1020, energyKcal: 241, fat: 0.5, saturates: 0.04,
    carbohydrate: 53, sugars: 47, protein: 3.4, salt: 0.03, fibre: 7.3,
    durabilityKind: 'DDM',
    storageConditionsFr: 'À conserver dans un endroit frais et sec.',
    usageInstructionsFr: null,
    priceCents: 550, vatCategory: 'FOOD_REDUCED', shippingWeightGrams: 280, isFeatured: false,
  },
  {
    slug: 'pistaches-grillees-250g',
    categorySlug: 'fruits-secs-noix',
    displayNameFr: 'Pistaches grillées salées 250 g',
    displayNameEn: 'Roasted salted pistachios 250 g',
    displayNameAr: 'فستق حلبي مشوي ٢٥٠ غ',
    legalName: 'Pistaches grillées salées en coque',
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: 'Grillées et salées à sec, en coque ouverte.',
    ingredientsFr: '**Pistaches** 98 %, sel.',
    allergens: ['NUTS'],
    mayContain: ['PEANUTS', 'SESAME'],
    quidFr: 'Pistaches 98 %',
    netQuantityValue: 250, netQuantityUnit: 'G', netQuantityDrained: null,
    energyKj: 2420, energyKcal: 580, fat: 46, saturates: 5.6,
    carbohydrate: 17, sugars: 8, protein: 21, salt: 1.0, fibre: 10,
    durabilityKind: 'DDM',
    storageConditionsFr: 'À conserver dans un endroit frais et sec.',
    usageInstructionsFr: null,
    priceCents: 890, vatCategory: 'FOOD_REDUCED', shippingWeightGrams: 290, isFeatured: false,
  },
  {
    slug: 'sumac-100g',
    categorySlug: 'epices-herbes',
    displayNameFr: 'Sumac moulu 100 g',
    displayNameEn: 'Ground sumac 100 g',
    displayNameAr: 'سماق مطحون ١٠٠ غ',
    legalName: 'Baies de sumac moulues',
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: 'Acidulé, pourpre. Sur le fattoush, le poulet, les oignons.',
    ingredientsFr: 'Baies de sumac moulues 100 %.',
    allergens: [],
    mayContain: ['SESAME'],
    quidFr: null,
    netQuantityValue: 100, netQuantityUnit: 'G', netQuantityDrained: null,
    energyKj: 1255, energyKcal: 300, fat: 15, saturates: 2,
    carbohydrate: 30, sugars: 3, protein: 5, salt: 0.1, fibre: 30,
    durabilityKind: 'DDM',
    storageConditionsFr: "À conserver dans un endroit frais et sec, à l'abri de la lumière.",
    usageInstructionsFr: null,
    priceCents: 390, vatCategory: 'FOOD_REDUCED', shippingWeightGrams: 130, isFeatured: false,
  },
  {
    slug: 'baklava-assortiment-500g',
    categorySlug: 'douceurs',
    displayNameFr: 'Baklava — assortiment 500 g',
    displayNameEn: 'Baklava assortment 500 g',
    displayNameAr: 'بقلاوة مشكلة ٥٠٠ غ',
    legalName: 'Assortiment de pâtisseries orientales à base de pâte filo et de fruits à coque',
    brand: null,
    countryOfOrigin: 'Liban',
    descriptionFr: 'Pistache, noix de cajou et noix, au sirop de fleur d\'oranger.',
    ingredientsFr:
      'Pâte filo (farine de **blé**, eau, sel), **pistaches** 18 %, **noix de cajou** 10 %, sucre, **beurre** clarifié, sirop de glucose, eau de fleur d\'oranger.',
    allergens: ['GLUTEN', 'NUTS', 'MILK'],
    mayContain: ['SESAME', 'EGGS'],
    quidFr: 'Pistaches 18 %, noix de cajou 10 %',
    netQuantityValue: 500, netQuantityUnit: 'G', netQuantityDrained: null,
    energyKj: 1880, energyKcal: 450, fat: 25, saturates: 8,
    carbohydrate: 48, sugars: 30, protein: 7, salt: 0.2, fibre: 2,
    durabilityKind: 'DDM',
    storageConditionsFr: 'À conserver dans un endroit frais et sec, à l\'abri de l\'humidité.',
    usageInstructionsFr: null,
    priceCents: 1290, vatCategory: 'CONFECTIONERY', shippingWeightGrams: 600, isFeatured: true,
  },
];
